### PR TITLE
add execute to fix #16 on example foo.js

### LINKED ISSUE #16: Is master broken?
Hi @martinheidegger, is master broken? I ran the example `foo` adventure like this:

```
git clone git@github.com:workshopper/workshopper-adventure.git
cd workshopper-adventure
npm install
examples/foo.js
<nothing>
```

### PR DESCRIPTION
**Pull request by tgfjt**

### CODE REVIEW

**Comment by martinheidegger** [comment]
Thanks

**Comment by martinheidegger** [comment]
Note: "fix #...." means that github will automatically close this issue! Please reference to line numbers or issues properly!

**Comment by martinheidegger** [comment]
Sorry for complaining, I was my mistake! I didn't realise that you try to fix #16 however it is at best a small measure to a larger problem. Thank you anyways!

**Comment by tgfjt** [comment]
Oh I went too far. I thought that this comment is good to control the issue but not need to close :bow:
Thank you for your telling me!

**Comment by martinheidegger** [comment]
Also i just realised that the example should pass in some arguments :)

**Pull request merged**
