### PR TITLE
Change package.json URL

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
I would like to contribute workshopper-adventure. But I could not find this repository.
Because [npm url](https://www.npmjs.com/package/workshopper-adventure)  does not show correct url...

### CODE REVIEW

**Comment by tgfjt** [comment]
I heard that this repo is just temporary will be merged to rvagg/Workshopper.

**Comment by yosuke-furukawa** [comment]
oh, if that is true, feel free to close this issue. thanks.

**Comment by watilde** [comment]
+1
It will merge or not, it might not be a fetters

**Comment by tgfjt** [comment]
ref: https://github.com/rvagg/workshopper/pull/106

**Pull request closed without merging**
