### PR TITLE
Master refactoring

### PR DESCRIPTION
**Pull request by martinheidegger**
Some code refactoring I have been working on.

### CODE REVIEW

**Comment by phillipj** [comment]
I'm doing a test run of this branch now, will post what I find as their own comment as I go..

First off is the border below the menu header, before vs after refactor:

skjermbilde 2015-09-29 kl 22 31 25
skjermbilde 2015-09-29 kl 22 31 42

**Comment by phillipj** [comment]
Verifying doesnt seem to work?

``` bash
→ javascripting verify introduction.js 
/../javascripting/node_modules/workshopper-adventure/index.js:153
      var remaining = this.countRemaining()
                           ^

TypeError: this.countRemaining is not a function
    at Immediate._onImmediate (/../javascripting/node_modules/workshopper-adventure/index.js:153:28)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by claudiopro** [comment]
@martinheidegger Whoa this is a big change. Are you using ES6 syntax perchance? I'm dabbling with it, but I'd hold off if this is going to land.

**Comment by martinheidegger** [comment]
@phillipj I have fixed quite a few bugs since you last tested it, I think. But the double line in javascript keeps being persistent (looking for it now)

@claudiopro es6 syntax for what?

**Comment by martinheidegger** [comment]
@phillipj I fixed the headline problem and verify does work for me now.

**Comment by martinheidegger** [comment]
Thank you for following this thread. I finally decided to publish workshopper-adventure 4.0.0

**Comment by tgfjt** [comment]
Great work:clap:

**Comment by claudiopro** [comment]
:+1:

**Pull request merged**
